version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: todo-mysql
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=potato
            - MYSQL_DATABASE=todo
            - MYSQL_USER=tse
            - MYSQL_PASSWORD=potato
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        container_name: todo-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8081:80

    php-fpm:
        build: docker/php-fpm
        container_name: todo-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
